plugins {
	id 'idea'
	id 'maven-publish'
	alias libs.plugins.fabric.loom
}

def ENV = System.getenv()
def NOW = new Date()
def buildTime = ENV.BUILD_TIME ?: NOW.format('yy.MMdd.HHmm')

def javaVersion = 21

group = maven_group_id

boolean isPreviewBuild = !ENV.TAG || ENV.TAG.matches(".+-.+")
def buildNumber = !ENV.TAG ? ("${ENV.BUILD_NUMBER ? "build.${ENV.BUILD_NUMBER}" : buildTime}-${libs.versions.minecraft.get()}") : ""
version = (ENV.TAG ?: "development") + ((isPreviewBuild && !ENV.TAG) ? "+${buildNumber}" : "")

println("Building ${project.name} ${version}")

repositories {
	maven {
		name = "NeoForged"
		url = "https://maven.neoforged.net/releases"
	}
	maven {
		name = "ParchmentMC"
		url = "https://maven.parchmentmc.org"
	}
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com"
	}
	maven {
		name = "Ladysnake"
		url = "https://maven.ladysnake.org/releases"
	}
	maven {
		name = "Lopa"
		url = "https://maven.uuid.gg/releases"
	}
	maven {
		name = "Team Resourceful"
		url = "https://maven.teamresourceful.com/repository/maven-public"
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "CurseMaven"
				url = "https://cursemaven.com"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	maven {
		name = "Gegy"
		url = "https://maven.gegy.dev"
	}
	maven {
		name = "Gserv"
		url = "https://jm.gserv.me/repository/maven-public/"
	}
}

dependencies {
	minecraft libs.minecraft

	mappings loom.layered() {
		officialMojangMappings()
		parchment "org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip"
	}

	compileOnly libs.jetbrains.annotations
	compileOnly libs.autoservice.annotations

	annotationProcessor libs.autoservice

	modImplementation libs.fabric.loader
	modImplementation libs.fabric.api

	modImplementation libs.sparkweave

	modImplementation libs.bundles.cca

	modImplementation libs.trinkets

	modImplementation libs.resourceful.config

	modImplementation libs.common.network.fabric

	modImplementation libs.datasync.fabric
	include libs.datasync.fabric

	// first person model
	modCompileOnly libs.firstperson

	// sodium
	modCompileOnly libs.sodium
	modLocalRuntime libs.sodium

	// iris
	modCompileOnly libs.iris
	modLocalRuntime libs.iris

	// lambdynamiclights
	modCompileOnly(libs.lambdynamiclights) {
		capabilities {
			requireCapability("dev.lambdaurora.lambdynamiclights:api-mojmap")
		}
	}

	// explosive enhancement
	modCompileOnly libs.explosive.enhancement

	// modmenu
	modCompileOnly libs.modmenu
	modLocalRuntime libs.modmenu

	// emi
	modCompileOnly variantOf(libs.emi) { classifier 'api' }
	modLocalRuntime libs.emi

	modLocalRuntime libs.yeetus.experimentus.fabric
}

loom {
	mods {
		"${mod_id}" {
			// Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
			sourceSet("main")
		}
	}

	accessWidenerPath.set(project.file("src/main/resources/${mod_id}.accesswidener"))

	runs {
		client {
			ideConfigGenerated(true)
			runDir("run")

			if (project.hasProperty('mc_uuid')) {
				programArg("--uuid=${project.findProperty('mc_uuid')}")
			}

			if (project.hasProperty('mc_username')) {
				programArg("--username=${project.findProperty('mc_username')}")
			}

			if (project.hasProperty('mc_java_agent_path')) {
				vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		datagen {
			client()
			setConfigName("Fabric Data Generation")

			property("fabric-api.datagen")
			property("fabric-api.datagen.strict-validation", "true") // '--all' sets '--validate' to true as well
			property("fabric-api.datagen.output-dir", file("src/main/generated").absolutePath)
			property("sparkweave.datagen.mods", "${mod_id}")
			runDir("build/datagen")
		}
	}
}

tasks.register('generateDatagenDir') {
	inputs.dir(project.layout.buildDirectory.dir("datagen"))

	doFirst {
		inputs.files.forEach { it.mkdirs() }
	}
}

tasks.ideaSyncTask.finalizedBy(tasks.generateDatagenDir)
tasks.runDatagen.dependsOn(tasks.generateDatagenDir)
sourceSets.main.resources { srcDir "src/main/generated" }

processResources {
	filteringCharset = "UTF-8"

	def expandProps = [
		"version"              : version,
		"maven_group_id"       : maven_group_id,
		"mod_id"               : mod_id,
		"mod_display_name"     : mod_display_name,
		"mod_description"      : mod_description,
		"sources_url"          : sources_url,
		"issues_url"           : issues_url,
		"license_url"          : license_url,
		"discord_url"          : discord_url,
		"homepage_url"         : homepage_url,

		"minecraft_version"    : libs.versions.minecraft.get(),
		"fabric_loader_version": libs.versions.fabric.loader.get(),
		"java_version"         : "${javaVersion}",
	]

	filesMatching(["fabric.mod.json", "*.mixins.json"]) {
		expand expandProps
	}

	inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release.set(javaVersion)
}

base {
	archivesName = "${project.name}-Fabric"
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(javaVersion)
		vendor = JvmVendorSpec.MICROSOFT
	}
}

jar {
	from(layout.projectDirectory) {
		include "LICENSE.md"
		rename "LICENSE.md", "LICENSE_${mod_id}.md"
	}

	manifest {
		attributes([
			'Specification-Title'     : rootProject.name,
			'Specification-Version'   : project.version,
			'Implementation-Title'    : "${project.name}",
			'Maven-Artifact'          : "${maven_group_id}:${project.name}:${project.version}",
			'Implementation-Version'  : project.version,
			'Implementation-Timestamp': NOW.format("yyyy-MM-dd'T'HH:mm:ssZ"),
			'Timestamp'               : NOW.toInstant().toEpochMilli(),
			'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
			'Built-On-Minecraft'      : libs.versions.minecraft.get()
		])
	}
}

sourcesJar {
	from(layout.projectDirectory) {
		include "LICENSE.md"
		rename "LICENSE.md", "LICENSE_${mod_id}.md"
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = "Arcanus-Fabric"
			from components.java
		}
	}

	repositories {
		if (ENV.MAVEN_UPLOAD_URL) {
			maven {
				url = ENV.MAVEN_UPLOAD_URL
				credentials {
					username = ENV.MAVEN_UPLOAD_USERNAME
					password = ENV.MAVEN_UPLOAD_PASSWORD
				}
			}
		}
	}
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}
