# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Metadata
group=dev.cammiescorner.arcanus
mod_id=arcanus
mod_description=A simple magic mod with player-made spells and Wynncraft-like casting.
mod_display_name=Arcanus
sources_url=https://github.com/CammiesCorner/Arcanus
issues_url=https://github.com/CammiesCorner/Arcanus/issues
license_url=https://github.com/CammiesCorner/Arcanus/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://cammiescorner.dev
curseforge_id=905345
modrinth_id=UnnRjucf
