# Gradle Properties
org.gradle.jvmargs=-Xmx2G
#org.gradle.configuration-cache=true
org.gradle.caching=true
mod_id=arcanuscontinuum
maven_group_id=dev.cammiescorner.arcanuscontinuum
mod_display_name=Arcanus
mod_description=A simple magic mod with player-made spells and Wynncraft-like casting.
sources_url=https://github.com/Up-Mods/Arcanus
issues_url=https://github.com/Up-Mods/Arcanus/issues
license_url=https://github.com/Up-Mods/Arcanus/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://cammiescorner.dev
