[versions]
fabric_loom = "1.10.5"

minecraft = "1.21.1"
fabric_loader = "0.16.13"

# https://parchmentmc.org/docs/getting-started
parchment_minecraft = "1.21.1"
parchment_mappings = "2024.11.17"

# environment stuff
jetbrains_annotations = "26.0.1"
autoservice = "1.1.1"

# misc
yeetus_experimentus_fabric = "b7C4gGUr" # [FABRIC][1.21] YeetusExperimentus 87.0.0
yeetus_experimentus_neoforge = "HaaH232J" # [NEOFORGE][1.21] YeetusExperimentus 87.0.0

# required dependencies
fabric_api = "0.115.4+1.21.1"
cca = "6.1.2"
sparkweave = "0.509.3"
resourceful_config = "3.0.11"
common_network = "1.0.18-1.21.1"
datasync = "0.10.0"
trinkets = "3.10.0"

# added compat
modmenu = "11.0.3"
emi = "1.1.22+1.21.1"
firstperson = "5nFUshwm" # 2.4.9
lambdynamiclights = "4.1.3+1.21.1"
explosive_enhancement = "1.3.2-1.21-1.21.1"
sodium = "mc1.21.1-0.6.13-fabric"
iris = "1.8.8+1.21.1-fabric"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }
autoservice_annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
cca_base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca_block = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-block", version.ref = "cca" }
cca_chunk = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-chunk", version.ref = "cca" }
cca_entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
cca_scoreboard = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-scoreboard", version.ref = "cca" }
sparkweave = { module = "dev.upcraft.sparkweave:Sparkweave-Fabric", version.ref = "sparkweave" }
datasync_fabric = { module = "dev.upcraft.datasync:datasync-minecraft-1.21.1-fabric", version.ref = "datasync" }
resourceful_config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21", version.ref = "resourceful_config" }
common_network_fabric = { module = "mysticdrew:common-networking-fabric", version.ref = "common_network" }
trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
firstperson = { module = "maven.modrinth:first-person-model", version.ref = "firstperson" }
lambdynamiclights = { module = "dev.lambdaurora.lambdynamiclights:lambdynamiclights-api", version.ref = "lambdynamiclights" }
explosive_enhancement = { module = "maven.modrinth:explosive-enhancement", version.ref = "explosive_enhancement" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }

yeetus_experimentus_fabric = { module = "maven.modrinth:yeetus-experimentus", version.ref = "yeetus_experimentus_fabric" }
yeetus_experimentus_neoforge = { module = "maven.modrinth:yeetus-experimentus", version.ref = "yeetus_experimentus_neoforge" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
cca = ["cca_base", "cca_block", "cca_chunk", "cca_entity", "cca_scoreboard"]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
