[versions]
fabric_loom = "1.9.2"

minecraft = "1.20.1"
fabric_loader = "0.16.10"

# https://parchmentmc.org/docs/getting-started
parchment_minecraft = "1.20.1"
parchment_mappings = "2023.09.03"

jetbrains_annotations = "26.0.1"
fabric_api = "0.92.3+1.20.1"
cca = "5.2.3"
sparkweave = "0.8.4"
patchouli = "1.20.1-84-FABRIC"
reach_attr = "2.4.0"
modmenu = "7.2.2"
emi = "1.1.18+1.20.1"
lazydfu = "0.1.3"
resourceful_config = "2.1.2"
firstperson = "Ca1G2C1x" # 2.4.8
pehkui = "3.7.8+1.14.4-1.20.1"
kanos = "0.4.1"
lambdynamiclights = "2.3.2+1.20.1"
spruceui = "5.0.2+1.20"
sodium = "mc1.20.1-0.5.3"
iris = "1.6.11+1.20.1"
explosive_enhancement = "1.2.2-1.20.x"
datasync = "0.9.0"
trinkets = "3.7.1" # refmap doesnt work on 3.7.2

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
cca_base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca_block = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-block", version.ref = "cca" }
cca_chunk = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-chunk", version.ref = "cca" }
cca_entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
cca_scoreboard = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-scoreboard", version.ref = "cca" }
sparkweave = { module = "dev.upcraft.sparkweave:Sparkweave-Fabric", version.ref = "sparkweave" }
patchouli = { module = "vazkii.patchouli:Patchouli", version.ref = "patchouli" }
reach_attr = { module = "com.jamieswhiteshirt:reach-entity-attributes", version.ref = "reach_attr" }
datasync_fabric = { module = "dev.upcraft.datasync:datasync-minecraft-1.20.1-fabric", version.ref = "datasync" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }
resourceful_config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.20.1", version.ref = "resourceful_config" }
firstperson = { module = "maven.modrinth:first-person-model", version.ref = "firstperson" }
pehkui = { module = "maven.modrinth:pehkui", version.ref = "pehkui" }
kanos = { module = "com.github.Virtuoel:KanosConfig", version.ref = "kanos" }
lambdynamiclights = { module = "maven.modrinth:lambdynamiclights", version.ref = "lambdynamiclights" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
explosive_enhancement = { module = "maven.modrinth:explosive-enhancement", version.ref = "explosive_enhancement" }
trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
cca = ["cca_base", "cca_block", "cca_chunk", "cca_entity", "cca_scoreboard"]
lambdynamiclights_runtime = ["lambdynamiclights", "spruceui"]
pehkui_runtime = ["pehkui", "kanos"]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
