modLoader = "javafml"
loaderVersion = "*"
license = "${license_url}" # Review your options at https://choosealicense.com
issueTrackerURL = "${issues_url}"
sourcesUrl = "${sources_url}" # custom property that we parse ourselves

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_display_name}"
displayURL = "${homepage_url}"
logoFile = "icon.png"
#credits = "" #optional
authors = "Up"
description = '''${mod_description}''' # Supports multiline text

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

# https://docs.neoforged.net/docs/gettingstarted/modfiles#dependency-configurations
[dependencies]
"${mod_id}" = [
    { modId = "neoforge", versionRange = "[${neoforge_version},)" },
    { modId = "minecraft", versionRange = "[${minecraft_version}]" },
    { modId = "sparkweave", mc-publish = { curseforge = "911456", modrinth = "nf68xfAw" } },
    { modId = "resourcefulconfig", mc-publish = { curseforge = "714059", modrinth = "M1953qlQ" } },
]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
[features.${mod_id}]
#openGLVersion="[3.2,)"
javaVersion = "[${java_version},)"

[mc-publish]
curseforge = "${curseforge_id}"
modrinth = "${modrinth_id}"
loaders = ["neoforge"]
